List<Map> listOfAllDoctors = [
  {
    "resourceType": "Practitioner",
    "id": "1552",
    "familyName": "SOUTH",
    "givenName": "John",
    "suffix": "MD",
    "phone": "9207129561",
    "addFirstLine": "12 SOUTH STREET",
    "city": "GREEN BAY",
    "state": "WI",
    "postalCode": "541550123",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1553",
    "familyName": "LAMBERT",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6144545656",
    "addFirstLine": "1202 EXECUTIVE WY",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430171234",
    "country": "USA",
    "gender": "female"
  },
  {
    "resourceType": "Practitioner",
    "id": "1554",
    "familyName": "YANKEE",
    "givenName": "John",
    "suffix": "MD",
    "phone": "2125553131",
    "addFirstLine": "1001 WEST 155TH",
    "city": "NEW YOURK CITY",
    "state": "NY",
    "postalCode": "100108123",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1555",
    "familyName": "YIN",
    "givenName": "John",
    "suffix": "NP",
    "phone": "8123401923",
    "addFirstLine": "4129 SOUTH ST",
    "city": "SAN MANTEO",
    "state": "CA",
    "postalCode": "999994129",
    "country": "USA",
    "gender": "male"
  },
  {
    "resourceType": "Practitioner",
    "id": "1557",
    "familyName": "PIZZA",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6129763742",
    "addFirstLine": "1001 MICHIGAN AV",
    "city": "CHICAGO",
    "state": "IL",
    "postalCode": "541550974",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1558",
    "familyName": "BAPTIST",
    "givenName": "John",
    "suffix": "MD",
    "phone": "9204561234",
    "addFirstLine": "1908 CHURCH GONEWAY",
    "city": "GREEN BAY",
    "state": "WI",
    "postalCode": "541550987",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1559",
    "familyName": "HOMERUN",
    "givenName": "John",
    "suffix": "MD",
    "phone": "4149029122",
    "addFirstLine": "904 BREWER WAY",
    "city": "MILWAUKEE",
    "state": "WI",
    "postalCode": "550219040",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1560",
    "familyName": "GRIMMEL",
    "givenName": "John",
    "suffix": "DO",
    "phone": "2125559321",
    "addFirstLine": "51272 BRIDGE STRET",
    "city": "SAN FRANCISCO",
    "state": "CA",
    "postalCode": "999995127",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1561",
    "familyName": "CASTLE",
    "givenName": "John",
    "suffix": "MD",
    "phone": "9204240213",
    "addFirstLine": "123 TOOTH DRIVE",
    "city": "GREEN BAY",
    "state": "WI",
    "postalCode": "541551234",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1562",
    "familyName": "EVIL",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6147161600",
    "addFirstLine": "100 SELDOM SEEN",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430177213",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1563",
    "familyName": "ALEGENT",
    "givenName": "John",
    "suffix": "NP",
    "phone": "6145551215",
    "addFirstLine": "4000 GRANGER ROA",
    "city": "DULBIN",
    "state": "OH",
    "postalCode": "430171234",
    "country": "USA",
    "gender": "female"
  },
  {
    "resourceType": "Practitioner",
    "id": "1564",
    "familyName": "STAF",
    "givenName": "John",
    "suffix": "MD",
    "phone": "9203214567",
    "addFirstLine": "1002 PACKERLAND RIVE",
    "city": "GREEN BAY",
    "state": "WI",
    "postalCode": "541551234",
    "country": "USA",
    "gender": "male"
  },
  {
    "resourceType": "Practitioner",
    "id": "1565",
    "familyName": "ALLISON",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6145551212",
    "addFirstLine": "123 MAIN STREET",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430171234",
    "country": "USA",
    "gender": "male"
  },
  {
    "resourceType": "Practitioner",
    "id": "1566",
    "familyName": "MARTIN",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6142131234",
    "addFirstLine": "8120 WEST 57TH",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430171234",
    "country": "USA",
    "gender": "male"
  },
  {
    "resourceType": "Practitioner",
    "id": "1567",
    "familyName": "ANAHEIM",
    "givenName": "John",
    "suffix": "MD",
    "phone": "2122308756",
    "addFirstLine": "1000 HOSPITAL WA",
    "city": "ANAHEIM",
    "state": "CA",
    "postalCode": "999991234",
    "country": "USA",
    "gender": "other"
  },
  {
    "resourceType": "Practitioner",
    "id": "1568",
    "familyName": "ACME",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6145551212",
    "addFirstLine": "1001 HOSPITAL DRVE",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430171234",
    "country": "USA",
    "gender": "male"
  },
  {
    "resourceType": "Practitioner",
    "id": "1569",
    "familyName": "EMORY",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6147651212",
    "addFirstLine": "2002 EAST DRIVE",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430171234",
    "country": "USA",
    "gender": "unknown"
  },
  {
    "resourceType": "Practitioner",
    "id": "1570",
    "familyName": "GUFFIDA",
    "givenName": "John",
    "suffix": "MD",
    "phone": "2125550987",
    "addFirstLine": "9012 RODEO DRIVE",
    "city": "BEVERLY HILLS",
    "state": "CA",
    "postalCode": "902107890",
    "country": "USA",
    "gender": "female"
  },
  {
    "resourceType": "Practitioner",
    "id": "1571",
    "familyName": "AKRON",
    "givenName": "John",
    "suffix": "MD",
    "phone": "6145551216",
    "addFirstLine": "3456 WEST 15TH",
    "city": "DUBLIN",
    "state": "OH",
    "postalCode": "430261234",
    "country": "USA",
    "gender": "male"
  }
];
